apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: certmonger
  name: certmonger
  namespace: certificate-tool
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'certmonger:latest'
      namespace: certificate-tool
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: docker
    git:
      uri: 'https://github.com/avoigtma/openshift-certmonger.git'
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile-ose-cli-certmonger.docker
      from:
        kind: ImageStreamTag
        name: 'centos:latest'
        namespace: openshift
      noCache: true
    type: Docker
  triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: 'centos:latest'
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
