apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: process-certrequests
  namespace: certificate-tool
spec:
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 0
      completions: 1
      parallelism: 1
      template:
        spec:
          containers:
            - command:
                - /bin/bash
                - '-c'
                - |
                  #/bin/bash
                  # workaround: ose-cli image sets $HOME to "/" which is not writable and prevents 'oc' to create $HOME/.kube directory
                  # hence we set to writable '/tmp' directory
                  export HOME=/tmp
                  #
                  . /tools/cm/cronProcess.sh
              image: 'image-registry.openshift-image-registry.svc:5000/certificate-tool/certmonger:latest'
              imagePullPolicy: Always
              name: certmonger
              volumeMounts:
                - mountPath: /tools/cm
                  name: script
                  readOnly: true
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 0
          serviceAccountName: certmonger-job-sa
          volumes:
            - configMap:
                name: cronjob-process-script
              name: script
  schedule: '*/2 * * * *'
  successfulJobsHistoryLimit: 3
