apiVersion: batch/v1
kind: Job
metadata:
  name: certmonger
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 1800
  backoffLimit: 2
  template:
    metadata:
      name: certmonger
    spec:
      containers:
      - name: certmonger
        image: image-registry.openshift-image-registry.svc:5000/cert-route/certmonger:latest
        command:
          - /bin/bash
          - -c
          - |
            #/bin/bash
            selfsign-getcert request -w -f /tmp/demo-server.crt -k /tmp/demo-server.key -N "CN=ocp.bla.example.com,OU=example.com,O=myorg" -D "ocp.bla.example.com" -U id-kp-serverAuth
            ls -l /tmp
      restartPolicy: OnFailure
      serviceAccount: certmonger-job-sa
      securityContext:
        runAsUser: 0
