apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ''
  labels:
    openshift.io/cluster-logging: 'true'
    openshift.io/cluster-monitoring: 'true'
  name: certificate-tool
