apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: certcreation-request-template
message: This templates instantiates a Job requesting a TLS certificate using 'certmonger' tool from a SCEP API for usage with a route in a target namespace. The certificate is placed in a Secret.
metadata:
  annotations:
    description: This templates instantiates data for triggering the creation of a route in a target namespace and requests a route-specific TLS certificate using 'certmonger' tool from a SCEP API.
    iconClass: icon-none
    openshift.io/display-name: Certificate Creation Request Template
    template.openshift.io/documentation-url: TODO
    template.openshift.io/long-description: This templates instantiates a Job requesting a TLS certificate using 'certmonger' tool from a SCEP API for usage with a route in a target namespace. The certificate is placed in a Secret.
    template.openshift.io/provider-display-name: TODO
    template.openshift.io/support-url: TODO
  name: certcreation-request-template
  namespace: openshift
objects:
  - apiVersion: v1
    data:
      appcmname: 'route-task-${CMAPPUUID}'
      targetNamespace: '${TARGET_NAMESPACE}'
      taskuuid: '${TASKUUID}'
      toolNamespace: '${TOOL_NAMESPACE}'
    kind: ConfigMap
    metadata:
      name: 'route-task-${CMTOOLSUUID}'
      namespace: '${TOOL_NAMESPACE}'
  - apiVersion: v1
    data:
      fqdn: '${FQDN}'
      routeIdentifier: '${CERT_IDENTIFIER}'
      routeType: none
      targetNamespace: '${TARGET_NAMESPACE}'
      taskuuid: '${TASKUUID}'
      toolNamespace: '${TOOL_NAMESPACE}'
    kind: ConfigMap
    metadata:
      name: 'route-task-${CMAPPUUID}'
      namespace: '${TARGET_NAMESPACE}'
parameters:
  - description: The namespace name where the route is being created.
    name: TARGET_NAMESPACE
    required: true
  - description: The name (identifier) of the secret object to be created for the certificate. Will be prefixed with 'route-' and postfixed with '-certs'.
    name: CERT_IDENTIFIER
    required: true
  - description: 'The FQDN of the route to be created. Ensure the length adheres to OpenShift / DNS conventions, i.e., max length 63 characters.'
    name: FQDN
    required: true
  - description: The namespace of where the route creation tool is running. Change only if you are sure the tool is deployed in a specific different namespace.
    name: TOOL_NAMESPACE
    value: certificate-tool
  - description: uuid parameter for CM in tools namespace
    displayName: do-not-fill-in-will-be-generated-cmtoolsuuid
    from: '[a-z0-9]{8}'
    generate: expression
    name: CMTOOLSUUID
  - description: uuid parameter for CM in application namespace
    displayName: do-not-fill-in-will-be-generated-cmappuuid
    from: '[a-z0-9]{8}'
    generate: expression
    name: CMAPPUUID
  - description: uuid parameter for aligning tools and application namespace
    displayName: do-not-fill-in-will-be-generated-taskuuid
    from: '[a-z0-9]{16}'
    generate: expression
    name: TASKUUID
