apiVersion: v1
kind: Template
labels:
  template: routecreation-request-template
message: This templates instantiates a Job creating a route in a target namespace and requests a route-specific TLS certificate using 'certmonger' tool from a SCEP API.
metadata:
  annotations:
    description: This templates instantiates data for triggering the creation of a route in a target namespace and requests a route-specific TLS certificate using 'certmonger' tool from a SCEP API.
    iconClass: icon-none
    openshift.io/display-name: Route Creation Request Template
    template.openshift.io/documentation-url: TODO
    template.openshift.io/long-description: This templates instantiates data for triggering the creation of a route in a target namespace and requests a route-specific TLS certificate using 'certmonger' tool from a SCEP API.
    template.openshift.io/provider-display-name: TODO
    template.openshift.io/support-url: TODO
  name: routecreation-request-template
  namespace: openshift
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: route-task-${CMTOOLSUUID}
    namespace: ${TOOL_NAMESPACE}
  data:
    toolNamespace: ${TOOL_NAMESPACE}
    targetNamespace: ${TARGET_NAMESPACE}
    taskuuid: ${TASKUUID}
    appcmname: route-task-${CMAPPUUID}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: route-task-${CMAPPUUID}
    namespace: ${TARGET_NAMESPACE}
  data:
    toolNamespace: ${TOOL_NAMESPACE}
    targetNamespace: ${TARGET_NAMESPACE}
    serviceName: ${SERVICENAME}
    routeName: ${ROUTENAME}
    hostname: ${HOSTNAME}
    port: ${PORT}
    routeType: ${ROUTETYPE}
    reencSecretName: ${REENC_CA_SECRET}
    taskuuid: ${TASKUUID}
parameters:
- name: TARGET_NAMESPACE
  description: The namespace name where the route is being created.
  required: true
- name: SERVICENAME
  description: The name of the service object exposed by the route. This service already exists in the target namespace.
  required: true
- name: ROUTENAME
  description: The name of the route object to be created.
  required: true
- name: HOSTNAME
  description: The FQDN of the route to be created. Ensure the length adheres to OpenShift / DNS conventions, i.e., max length 63 characters.
  required: true
- name: PORT
  description: The port number of the inbound port of the service to which the route is pointing to.
  required: true
- name: ROUTETYPE
  description: The type of the route to be created. Use either 'edge', 'passthrough' or 'reencrypt'.
  required: true
  value: edge
- name: REENC_CA_SECRET
  description: The name of a secret in the target namespace which must contain a certificate for reencrypting traffic. Optional - must only be provided if ROUTETYPE='reencrypt'.
- name: TOOL_NAMESPACE
  description: The namespace of where the route creation tool is running. Change only if you are sure the tool is deployed in a specific different namespace.
  value: certificate-tool
- name: CMTOOLSUUID
  displayName: do-not-fill-in-will-be-generated-cmtoolsuuid
  description: uuid parameter for CM in tools namespace
  from: "[a-z0-9]{8}"
  generate: "expression"
- name: CMAPPUUID
  displayName: do-not-fill-in-will-be-generated-cmappuuid
  description: uuid parameter for CM in application namespace
  from: "[a-z0-9]{8}"
  generate: "expression"
- name: TASKUUID
  displayName: do-not-fill-in-will-be-generated-taskuuid
  description: uuid parameter for aligning tools and application namespace
  from: "[a-z0-9]{16}"
  generate: "expression"
