apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: routecreation-request-template
message: This templates instantiates a Job creating a route in a target namespace and requests a route-specific TLS certificate using 'certmonger' tool from a SCEP API.
metadata:
  annotations:
    description: This templates instantiates data for triggering the creation of a route in a target namespace and requests a route-specific TLS certificate using 'certmonger' tool from a SCEP API.
    iconClass: icon-none
    openshift.io/display-name: Route Creation Request Template
    template.openshift.io/documentation-url: https://github.com/avoigtma/openshift-certmonger
    template.openshift.io/long-description: This templates instantiates data for triggering the creation of a route in a target namespace and requests a route-specific TLS certificate using 'certmonger' tool from a SCEP API.
    template.openshift.io/provider-display-name: Andreas Voigtmann, https://github.com/avoigtma
    template.openshift.io/support-url: n/a
  name: routecreation-request-template
  namespace: openshift
objects:
  - apiVersion: v1
    data:
      appcmname: 'route-task-${CMAPPUUID}'
      targetNamespace: '${TARGET_NAMESPACE}'
      taskuuid: '${TASKUUID}'
      toolNamespace: '${TOOL_NAMESPACE}'
    kind: ConfigMap
    metadata:
      name: 'route-task-${CMTOOLSUUID}'
      namespace: '${TOOL_NAMESPACE}'
  - apiVersion: v1
    data:
      fqdn: '${FQDN}'
      san: '${SAN}'
      port: '${PORT}'
      reencSecretName: '${REENC_CA_SECRET}'
      routeIdentifier: '${ROUTE_IDENTIFIER}'
      routeType: '${ROUTETYPE}'
      serviceName: '${SERVICENAME}'
      targetNamespace: '${TARGET_NAMESPACE}'
      taskuuid: '${TASKUUID}'
      toolNamespace: '${TOOL_NAMESPACE}'
    kind: ConfigMap
    metadata:
      name: 'route-task-${CMAPPUUID}'
      namespace: '${TARGET_NAMESPACE}'
parameters:
  - description: The namespace name where the route is being created. This is usually the same as the namespace you see above.
    name: TARGET_NAMESPACE
    required: true
  - description: The name of the service object exposed by the route. This service already exists in the target namespace.
    name: SERVICENAME
    required: true
  - description: The name (identifier) of the route object to be created.
    name: ROUTE_IDENTIFIER
    required: true
  - description: 'The FQDN of the route to be created. Ensure the length adheres to OpenShift / DNS conventions, i.e., max length 63 characters.'
    name: FQDN
    required: true
  - description: 'Additional FQDNs to be included as SAN (Subject Alternate Name) in the certificate. If you want to set multiple SANs, specify each SAN FQN and separate by spaces. Value is optional.'
    name: SAN
  - description: The port number of the inbound port of the service to which the route is pointing to.
    name: PORT
    required: true
  - description: 'The type of the route to be created. Use either ''edge'', ''passthrough'', ''reencrypt'', or ''none''. If you specify ''none'', a certificate is requested and stored as a secret, but no route is being created.'
    name: ROUTETYPE
    required: true
    value: edge
  - description: The name of a secret in the target namespace which must contain a certificate for reencrypting traffic. Optional - must only be provided if ROUTETYPE='reencrypt'.
    name: REENC_CA_SECRET
  - description: The namespace of where the route creation tool is running. Change only if you are sure the tool is deployed in a specific different namespace.
    name: TOOL_NAMESPACE
    value: certificate-tool
  - description: uuid parameter for CM in tools namespace
    displayName: do-not-fill-in-will-be-generated-cmtoolsuuid
    from: '[a-z0-9]{8}'
    generate: expression
    name: CMTOOLSUUID
  - description: uuid parameter for CM in application namespace
    displayName: do-not-fill-in-will-be-generated-cmappuuid
    from: '[a-z0-9]{8}'
    generate: expression
    name: CMAPPUUID
  - description: uuid parameter for aligning tools and application namespace
    displayName: do-not-fill-in-will-be-generated-taskuuid
    from: '[a-z0-9]{16}'
    generate: expression
    name: TASKUUID
