apiVersion: v1
kind: Template
labels:
  template: job-routecreation-template
message: This templates instantiates a Job creating a route in a target namespace and requests a route-specific TLS certificate using 'certmonger' tool from a SCEP API.
metadata:
  annotations:
    description: This templates instantiates a Job creating a route in a target namespace and requests a route-specific TLS certificate using 'certmonger' tool from a SCEP API.
    iconClass: icon-none
    openshift.io/display-name: Job Application Template
    template.openshift.io/documentation-url: TODO
    template.openshift.io/long-description: This templates instantiates a Job creating a route in a target namespace and requests a route-specific TLS certificate using 'certmonger' tool from a SCEP API.
    template.openshift.io/provider-display-name: TODO
    template.openshift.io/support-url: TODO
  name: job-routecreation-template
  namespace: certificate-tool
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: 'certmonger-${JOBUUID}'
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 0
      completions: 1
      parallelism: 1
      template:
        metadata:
          name: 'certmonger-${JOBUUID}'
        spec:
          containers:
            - command:
                - /bin/bash
                - '-c'
                - |
                  #!/bin/bash
                  export SERVICENAME=${SERVICENAME}
                  export ROUTE_IDENTIFIER=${ROUTE_IDENTIFIER}
                  export ROUTETYPE=${ROUTETYPE}
                  export REENC_CA_SECRET=${REENC_CA_SECRET}
                  export TARGET_NAMESPACE=${TARGET_NAMESPACE}
                  export FQDN=${FQDN}
                  export PORT=${PORT}
                  export JOB=certmonger-${JOBUUID}
                  export TOOL_NAMESPACE=${TOOL_NAMESPACE}
                  . /tools/cm/runJob.sh
              env:
                - name: PKIPASSPHRASE
                  valueFrom:
                    secretKeyRef:
                      key: passphrase
                      name: pki-secret
              image: 'image-registry.openshift-image-registry.svc:5000/${TOOL_NAMESPACE}/certmonger:latest'
              name: certmonger
              volumeMounts:
                - mountPath: /tools/ca
                  name: ca
                  readOnly: true
                - mountPath: /tools/cm
                  name: script
                  readOnly: true
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 0
          serviceAccount: certmonger-job-sa
          volumes:
            - name: ca
              secret:
                secretName: ca-secret
            - configMap:
                name: route-creation-script
              name: script
parameters:
  - description: The namespace name where the route is being created.
    name: TARGET_NAMESPACE
    required: true
  - description: The name of the service object exposed by the route. This service already exists in the target namespace.
    name: SERVICENAME
    required: true
  - description: The name (identifier) of the route object to be created.
    name: ROUTE_IDENTIFIER
    required: true
  - description: 'The FQDN of the route to be created. Ensure the length adheres to OpenShift / DNS conventions, i.e., max length 63 characters.'
    name: FQDN
    required: true
  - description: The port number of the inbound port of the service to which the route is pointing to.
    name: PORT
    required: true
  - description: 'The type of the route to be created. Use either ''edge'', ''passthrough'', ''reencrypt'', or ''none''. If you specify ''none'', a certificate is requested and stored as a secret, but no route is being created.'
    name: ROUTETYPE
    required: true
    value: edge
  - description: The name of a secret in the target namespace which must contain a certificate for reencrypting traffic. Optional - must only be provided if ROUTETYPE='reencrypt'.
    name: REENC_CA_SECRET
  - description: The namespace of where the route creation tool is running. Change only if you are sure the tool is deployed in a specific different namespace.
    name: TOOL_NAMESPACE
    value: certificate-tool
  - description: The id for the job (matching the request uuid) performing the certificate request.
    name: JOBUUID
    required: true
